./views/sidebar.html:        <li ui-wave><a href="#/dashboard"> <i class="imd imd-home"></i><span data-translate="Home"></span> </a></li>
./views/header.html:            <span class="logo-icon imd imd-dashboard"></span>
./views/dashboard.html:<div class="page page-dashboard">
./views/ui/icons.html:                            <div class="col-lg-3 col-sm-4 col-xs-6"><p><i class="imd imd-dashboard"></i> md-dashboard</p></div>
./bower_components/bootstrap-material-design/bootstrap-elements.html:                    <div class="icon-preview"><i class="mdi-action-dashboard"></i><span>mdi-action-dashboard</span></div>
./scripts/core/config.route.js:                'dashboard',
./scripts/core/config.route.js:                //.when('/', '/dashboard')
./scripts/core/config.route.js:                .otherwise('/dashboard');
./bower_components/modernizr/feature-detects/es6/promises.js:    "name": "Chromium dashboard - ES6 Promises",
